version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakpassword
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  keycloak:
    image: keycloak/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_PORT: 3306
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    command: ["start-dev"]
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data

volumes:
  mysql_data:
  keycloak_data:
